<?php

namespace Greg\ReaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /*
     * Renvoie la liste des catégories avec leurs subs par ordre 
     */
    public function getCategories()
    {
        $query = $this->createQueryBuilder('a')
                ->leftJoin('a.subs', 's')
                ->addSelect('s')
                ->orderBy('a.name')
                ->getQuery();
        return $query->getResult();
    }
}
