<?php

namespace Greg\ReaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    function getItems($channelId)
    {
        if (!$channelId)
        {
            throw new \InvalidArgumentException("L'argument channelId n'est pas défini");
        }
        
        $query = $this->createQueryBuilder('f')
                ->where('f.channel_id = :subId')
                ->setParameter('channel_id', $subId);
    }
}
