<?php

namespace Greg\ReaderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubRepository extends EntityRepository
{
    
}
