blog_accueil:
    path: /{page}
    defaults: { _controller: GregBlogBundle:Blog:index, page: 1 }
    requirements:
      page: \d*
    
blog_voir:
    path: /article/{id}
    defaults: { _controller: GregBlogBundle:Blog:voir }
    requirements:
      id: \d+
    
blog_ajouter:
    path: /ajouter
    defaults: { _controller: GregBlogBundle:Blog:ajouter } 
    
blog_modifier:
    path: /modifier/{id}
    defaults: { _controller: GregBlogBundle:Blog:modifier }
    requirements: 
      id: \d+
      
blog_supprimer:
    path: /supprimer/{id}
    defaults: { _controller: GregBlogBundle:Blog:supprimer }
    requirements: 
      id: \d+
      
blog_envoimail:
    path: /mailer
    defaults: { _controller: GregBlogBundle:Blog:mailer }