parameters:
#    greg_blog.example.class: Greg\BlogBundle\Example

services:
#    greg_blog.example:
#        class: %greg_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
