reader_index:
    path:   /
    defaults: { _controller: GregReaderBundle:Reader:index }
    
reader_voir_sub:
    path:   /voir_sub/{id}
    defaults: { _controller: GregReaderBundle:Reader:voirSub }
    requirements:
        sub: \d*