reader_index:
    path:   /
    defaults: { _controller: GregReaderBundle:Reader:index }
    
reader_voir_channel:
    path:   /channel/{id}
    defaults: { _controller: GregReaderBundle:Reader:voirChannel }
    requirements:
        sub: \d*